baseURL = "https://ashawcker.github.com"
languageCode = "en"
title = "Anurag Sharma"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true

[pagination]
pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
